
name: kc-fundamentals-composetest
services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    environment:

      # Keycloak Admin User
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      # Logging, see: https://www.keycloak.org/server/logging
      KC_LOG_LEVEL: INFO

      # Postgres DB Configuration
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: postgres_user
      KC_DB_PASSWORD: postgres_pass

    volumes:
      - keycloak-data:/opt/keycloak/data:z

    ports:
      - 8080:8080   # HTTP

    networks:
      - backend

    command:
      - "--verbose"
      - "start-dev" # Only for Dev-Environment!

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pass
    ports:
        - 5432:5432
    networks:
      - backend
    volumes:
        - postgres-data:/var/lib/postgresql/data

networks:
  backend:

volumes:
  keycloak-data:
  postgres-data: