
name: kc-fundamentals-lab3-1
services:

#  oauth2-proxy:
#    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
#    restart: always
#    command:
#      - --http-address
#      - 0.0.0.0:4180
#    ports:
#      - 4180:4180/tcp
#    environment:
#      OAUTH2_PROXY_COOKIE_SECRET: "OQINaROshtE9TcZkNAm-5Zs2Pv3xaWytBmc5W7sPX7w="
#      OAUTH2_PROXY_PROVIDER: keycloak-oidc
#      OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: Keycloak
#      OAUTH2_PROXY_COOKIE_SECURE: false
#      OAUTH2_PROXY_PASS_ACCESS_TOKEN: true
#      OAUTH2_PROXY_UPSTREAMS: http://nginx:80/
#      OAUTH2_PROXY_SKIP_OIDC_DISCOVERY: true
#      OAUTH2_PROXY_OIDC_ISSUER_URL: http://localhost:8080/realms/proxy
#      OAUTH2_PROXY_REDIRECT_URL: http://localhost:4180/oauth2/callback
#      OAUTH2_PROXY_LOGIN_URL: http://localhost:8080/realms/proxy/protocol/openid-connect/auth
#      OAUTH2_PROXY_REDEEM_URL: http://keycloak:8080/realms/proxy/protocol/openid-connect/token
#      OAUTH2_PROXY_OIDC_JWKS_URL: http://keycloak:8080/realms/proxy/protocol/openid-connect/certs
#    networks:
#      - backend
#    depends_on:
#      keycloak:
#        condition: service_healthy

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - backend
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: INFO
      KC_HEALTH_ENABLED: true
    volumes:
      - keycloak-data:/opt/keycloak/data:z
    ports:
      - 8080:8080
      - 9000:9000
    networks:
      - backend
    command:
      - "--verbose"
      - "start-dev"
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/localhost/9000 && echo -e 'GET /health/ready HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3 && cat <&3 | grep -q '200 OK'" ]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 10s

networks:
  backend:

volumes:
  keycloak-data: