services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SET_ACL: TRUE
    ports:
      - 22181:2181

  kafka-broker-1:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - zookeeper
      - keycloak
    ports:
      - 9091:9091
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG4J_ROOT_LOGLEVEL: TRACE
      KAFKA_ADVERTISED_LISTENERS: INTERBROKER://kafka-broker-1:19091,KAFKAUI://kafka-broker-1:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERBROKER:PLAINTEXT,KAFKAUI:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERBROKER
      KAFKA_LISTENER_NAME_INTERBROKER_SASL_ENABLED_MECHANISMS: OAUTHBEARER

      # Konfiguration für Authentication-Server
      KAFKA_LISTENER_NAME_INTERBROKER_SASL_OAUTHBEARER_JWKS_ENDPOINT_URL: http://keycloak:8080/realms/kafka/protocol/openid-connect/certs
      KAFKA_LISTENER_NAME_INTERBROKER_SASL_OAUTHBEARER_EXPECTED_AUDIENCE: kafka-broker
      KAFKA_LISTENER_NAME_INTERBROKER_SASL_OAUTHBEARER_EXPECTED_ISSUER: http://keycloak:8080/realms/kafka
      KAFKA_LISTENER_NAME_INTERBROKER_OAUTHBEARER_SASL_LOGIN_CALLBACK_HANDLER_CLASS: org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginCallbackHandler
      KAFKA_LISTENER_NAME_INTERBROKER_SASL_OAUTHBEARER_TOKEN_ENDPOINT_URL: http://keycloak:8080/realms/kafka/protocol/openid-connect/token
      KAFKA_LISTENER_NAME_INTERBROKER_OAUTHBEARER_SASL_JAAS_CONFIG: org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required clientId="kafka-broker-1" clientSecret="your-secret" scope="profile";
      KAFKA_LISTENER_NAME_INTERBROKER_OAUTHBEARER_SASL_SERVER_CALLBACK_HANDLER_CLASS: org.apache.kafka.common.security.oauthbearer.OAuthBearerValidatorCallbackHandler
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: OAUTHBEARER
      
  kafka-broker-2:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - zookeeper
      - keycloak
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG4J_ROOT_LOGLEVEL: TRACE
      KAFKA_ADVERTISED_LISTENERS: INTERBROKER://kafka-broker-2:19092,KAFKAUI://kafka-broker-2:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERBROKER:PLAINTEXT,KAFKAUI:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERBROKER

      # Konfiguration für Authentication-Server
      KAFKA_LISTENER_NAME_INTERBROKER_SASL_ENABLED_MECHANISMS: OAUTHBEARER
      KAFKA_LISTENER_NAME_INTERBROKER_SASL_OAUTHBEARER_JWKS_ENDPOINT_URL: http://keycloak:8080/realms/kafka/protocol/openid-connect/certs
      KAFKA_LISTENER_NAME_INTERBROKER_SASL_OAUTHBEARER_EXPECTED_AUDIENCE: kafka-broker
      KAFKA_LISTENER_NAME_INTERBROKER_SASL_OAUTHBEARER_EXPECTED_ISSUER: http://keycloak:8080/realms/kafka
      KAFKA_LISTENER_NAME_INTERBROKER_SASL_OAUTHBEARER_TOKEN_ENDPOINT_URL: http://keycloak:8080/realms/kafka/protocol/openid-connect/token
      KAFKA_LISTENER_NAME_INTERBROKER_OAUTHBEARER_SASL_LOGIN_CALLBACK_HANDLER_CLASS: org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginCallbackHandler
      KAFKA_LISTENER_NAME_INTERBROKER_OAUTHBEARER_SASL_JAAS_CONFIG: org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required clientId="kafka-broker-2" clientSecret="your-secret" scope="profile";
      KAFKA_LISTENER_NAME_INTERBROKER_OAUTHBEARER_SASL_SERVER_CALLBACK_HANDLER_CLASS: org.apache.kafka.common.security.oauthbearer.OAuthBearerValidatorCallbackHandler
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: OAUTHBEARER

  kafka-ui:
    image: provectuslabs/kafka-ui
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
    ports:
      - 8082:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka-lab2.1
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker-1:9091

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: INFO
      JAVA_OPTS_APPEND: "--show-version"
      DEBUG: "true"
      DEBUG_PORT: "*:8787"
    ports:
      - 8080:8080
      - 8787:8787
    command:
      - "--verbose"
      - "start-dev"
