name: kc-mc-lab-abac
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.6.1
    environment:
      # Keycloak Admin User
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_FEATURES: scripts

      # Logging, see: https://www.keycloak.org/server/logging
      KC_LOG_LEVEL: INFO

    volumes:
      - keycloak-data:/opt/keycloak/data:z # Keycloak h2 database, not for production!
      - ./providers:/opt/keycloak/providers:z
      - ../realm-lab.json:/opt/keycloak/data/import/realm-lab.json

    ports:
      - 127.0.0.1:8080:8080 # HTTP

    networks:
      - backend

    command:
      - "--verbose"
      - "start-dev" # Only for Dev-Environment!
      - "--import-realm"

networks:
  backend:

volumes:
  keycloak-data:
