name: kc-mc-lab-configcli-solution
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.4
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: INFO
    volumes:
      - keycloak-data:/opt/keycloak/data:z
    ports:
      - "127.0.0.1:8080:8080"
    command:
      - "--verbose"
      - "start-dev"

  keycloak-config:
    profiles:
      - cli
    depends_on:
      - keycloak
    image: adorsys/keycloak-config-cli:latest-26.1.0
    environment:
      KEYCLOAK_URL: "http://keycloak:8080/"
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: true
      KEYCLOAK_AVAILABILITYCHECK_TIMEOUT: 5s
      IMPORT_FILES_LOCATIONS: "/config/*"
      IMPORT_VAR_SUBSTITUTION_ENABLED: "true"
      LASTNAME: "codecentric"
    volumes:
      - ./config:/config

volumes:
  keycloak-data:
