apiVersion: v1
kind: Pod
metadata:
  name: terraform-pod
  namespace: masterclass
spec:
  serviceAccountName: terraform
  containers:
    - name: terraform
      image: hashicorp/terraform:latest
      command: ["sleep", "3600"]
      workingDir: /terraform
      volumeMounts:
        - mountPath: /var/run/secrets/serviceaccount
          name: sa-token
  volumes:
    - name: sa-token
      projected:
        sources:
          - serviceAccountToken:
              audience: "http://keycloak-keycloakx-http/realms/master"
              expirationSeconds: 600
              path: token
